### ISSUE TITLE
extras links are dead

### ISSUE THREAD

**Issue by ildar** [adplug/adplug.github.io#3]
at least some of them

**Comment by Malvineous** [comment]
Which ones?  Where have the sites moved to?  Can you send a pull request with updated links?

**Comment by ildar** [comment]
I couldn't find them, hoped someone who knows could point out for
everybody's gain 🙁

**Comment by binarymaster** [comment]
I've updated dead links on Extras page.

The only one dead link http://mitglied.lycos.de/borgnumberone/misc/adlib/ is left, unfortunately it was not archived by Internet Archive.

**Comment by ildar** [comment]
Thanks a lot! 👍
